In [4]:
#Classification Problem
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [48]:
df = pd.read_csv('winequality-red.csv',sep=';')
df.rename(columns = {'fixed acidity':'fixedacidity'}, inplace = True) 
df.rename(columns = {'volatile acidity':'volatileacidity'}, inplace = True) 
df.rename(columns = {'citric acid':'citricacid'}, inplace = True) 
df.rename(columns = {'residual sugar':'residualsugar'}, inplace = True) 
df.rename(columns = {'free sulfur dioxide':'freesulfurdioxide'}, inplace = True) 
df.rename(columns = {'total sulfur dioxide':'totalsulfurdioxide'}, inplace = True)

In [49]:
df.head()

,fixedacidity,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [50]:
cols_normalize = ['fixedacidity', 'volatileacidity', 'citricacid', 'residualsugar',
       'chlorides', 'freesulfurdioxide', 'totalsulfurdioxide', 'density',
       'pH', 'sulphates', 'alcohol']

In [51]:
#We can use this function to normalize our data from a real-life datasets
df[cols_normalize] = df[cols_normalize].apply(lambda x : (x - x.min())/(x.max() - x.min()))

In [52]:
df.head()

,fixedacidity,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol,quality
0,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,5
1,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385,5
2,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385,5
3,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385,6
4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,5

In [86]:
df.groupby('quality').count()

,fixedacidity,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,10,10,10,10,10,10,10,10,10,10,10
4,53,53,53,53,53,53,53,53,53,53,53
5,681,681,681,681,681,681,681,681,681,681,681
6,638,638,638,638,638,638,638,638,638,638,638
7,199,199,199,199,199,199,199,199,199,199,199
8,18,18,18,18,18,18,18,18,18,18,18

In [87]:
#Inizializing Features
#Numerical Values
fixed_acidity = tf.feature_column.numeric_column('fixedacidity')
volatile_acidity =  tf.feature_column.numeric_column('volatileacidity')
citric_acid = tf.feature_column.numeric_column('citricacid')
residual_sugar = tf.feature_column.numeric_column('residualsugar')
chlorides = tf.feature_column.numeric_column('chlorides')
free_sulfur_dioxide = tf.feature_column.numeric_column('freesulfurdioxide')
total_sulfur_dioxide = tf.feature_column.numeric_column('totalsulfurdioxide')
density = tf.feature_column.numeric_column('density')
pH = tf.feature_column.numeric_column('pH')
sulphates = tf.feature_column.numeric_column('sulphates')
alcohol = tf.feature_column.numeric_column('alcohol')

In [88]:
#,citric_acid
feat_columns = [fixed_acidity,volatile_acidity,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,
               density,pH,sulphates,alcohol]

In [89]:
#Split our data for train test
X = df.drop('quality',axis = 1)
y = df['quality']

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [92]:
#lets create our functions for training and testing
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,
                                                 y=y_train,
                                                batch_size=10,
                                                num_epochs=1000,
                                                shuffle=True)

In [106]:
dense_nn_model = tf.estimator.DNNClassifier(hidden_units=[10,10,10,10,10,6],
                                            feature_columns=feat_columns,
                                           n_classes=6,label_vocabulary=['3','4','5','6','7','8'])

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\Muneeb\AppData\Local\Temp\tmphd7_oe7j
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Muneeb\\AppData\\Local\\Temp\\tmphd7_oe7j', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000180C6B395C8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [107]:
dense_nn_model.train(input_fn=input_func,steps = 1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Muneeb\AppData\Local\Temp\tmphd7_oe7j\model.ckpt.
INFO:tensorflow:loss = 18.56067, step = 1
INFO:tensorflow:global_step/sec: 212.785
INFO:tensorflow:loss = 8.372762, step = 101 (0.454 sec)
INFO:tensorflow:global_step/sec: 350.762
INFO:tensorflow:loss = 10.182099, step = 201 (0.301 sec)
INFO:tensorflow:global_step/sec: 332.528
INFO:tensorflow:loss = 6.949547, step = 301 (0.285 sec)
INFO:tensorflow:global_step/sec: 350.758
INFO:tensorflow:loss = 12.061871, step = 401 (0.301 sec)
INFO:tensorflow:global_step/sec: 332.541
INFO:tensorflow:loss = 13.820848, step = 501 (0.285 sec)
INFO:tensorflow:global_step/sec: 339.894
INFO:tensorflow:loss = 8.468266, step = 601 (0.301 sec)
INFO:tensorflow:global_step/sec: 350.761
INFO:tensorflow:loss = 10.828869, step = 701 (0.294 sec)
INFO:tensorflow:global_step/sec: 309.743
INFO:tensorflow:loss = 8.274898, step = 801 (0.307 sec)
INFO:tensorflow:global_step/sec: 332.536
INFO:tensorflow:loss = 6.8935475, step = 901 (0.316 sec)
INFO:tensorflow:Saving checkpoints for 1000 into C:\Users\Muneeb\AppData\Local\Temp\tmphd7_oe7j\model.ckpt.
INFO:tensorflow:Loss for final step: 7.1488776.

In [95]:
eval_input_fnc = tf.estimator.inputs.pandas_input_fn(x=X_test,
                                                    y=y_test,
                                                    batch_size=10,
                                                    num_epochs=1,
                                                    shuffle=False)

In [96]:
pred_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test,
                                                     batch_size=10,
                                                     num_epochs=1,
                                                     shuffle=False)

In [108]:
DNN_eval = dense_nn_model.evaluate(eval_input_fnc)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-09-28T21:19:58Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Muneeb\AppData\Local\Temp\tmphd7_oe7j\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2020-09-28-21:19:58
INFO:tensorflow:Saving dict for global step 1000: accuracy = 0.55, average_loss = 1.0268042, global_step = 1000, loss = 10.268043
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: C:\Users\Muneeb\AppData\Local\Temp\tmphd7_oe7j\model.ckpt-1000

In [109]:
DNN_eval

{'accuracy': 0.55,
 'average_loss': 1.0268042,
 'loss': 10.268043,
 'global_step': 1000}

In [110]:
Predictions_dnn = dense_nn_model.predict(pred_input_func)

In [111]:
conv_predictions_dnn = list(Predictions_dnn)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Muneeb\AppData\Local\Temp\tmphd7_oe7j\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

In [112]:
predict_class_id_dnn = []
for i in conv_predictions_dnn:
    for j in i['class_ids']:
        predict_class_id_dnn.append(j)

In [113]:
original_test_data = []
for i in y_test:
    original_test_data.append(i)

In [114]:
print('original,predict')
for i,j in zip(original_test_data,predict_class_id_dnn):
    print(i,'  ',j)

original,predict
5    2
5    2
5    2
7    3
6    3
6    4
5    3
7    3
6    3
5    2
7    2
5    3
5    3
5    2
6    2
5    2
4    3
3    2
5    2
6    2
7    3
7    3
6    2
5    3
4    3
5    2
5    2
5    2
6    4
6    2
6    2
5    2
6    2
6    2
6    2
5    4
5    3
6    3
4    2
3    2
6    4
5    2
6    3
6    3
6    3
6    3
5    3
6    3
5    2
5    2
4    2
7    3
5    2
5    2
6    2
5    3
6    3
7    3
6    4
7    4
5    2
6    2
5    2
5    2
5    2
7    3
5    2
6    2
5    2
5    3
6    2
5    2
6    3
6    3
5    2
5    4
6    2
6    4
5    2
6    3
5    2
6    3
5    2
6    2
7    3
5    2
4    2
6    3
5    2
5    2
6    4
6    3
4    2
6    3
7    3
6    2
6    2
5    3
5    2
6    3
5    2
6    3
5    2
7    3
5    2
6    2
5    2
6    2
5    2
6    4
6    2
5    3
5    2
7    3
5    2
6    3
6    3
5    2
6    2
5    2
6    3
4    2
5    2
6    4
7    2
4    2
6    3
5    2
5    3
6    2
6    2
5    2
8    4
6    3
5    2
7    4
5    2
7    3
6    3
5    4
5    2
5    2
6    2
4    2
5    2
8    4
5    3
6    3
6    3
5    2
5    2
6    3
5    2
6    3
5    2
5    2
5    2
6    2
6    3
5    2
5    2
5    2
4    2
5    2
7    2
6    3
6    3
7    3
5    3
5    3
5    2
6    3
5    4
5    2
6    3
6    4
7    3
5    2
7    3
5    2
7    3
6    2
5    2
5    2
6    3
6    2
6    2
6    3
7    3
5    2
6    3
6    4
6    2
6    3
5    3
7    3
7    2
6    2
6    3
6    3
5    2
6    4
5    2
7    4
5    3
5    2
6    3
5    3
5    3
7    3
6    3
5    2
7    4
3    2
6    2
7    3
5    2
6    3
5    2
5    2
5    2
7    4
6    2
6    2
6    3
6    3
7    4
6    2
7    3
4    3
5    2
6    2
7    3
5    2
5    2
5    2
6    3
6    2
5    2
6    2
6    2
5    3
7    3
5    2
5    2
4    2
5    2
7    4
5    2
5    3
6    2
4    3
5    2
5    2
6    2
6    2
4    3
5    2
5    3
6    4
4    2
6    4
5    2
5    2
5    2
5    3
5    2
5    2
6    3
7    4
6    2
6    3
6    3
5    2
6    3
5    2
6    2
6    3
6    2
6    2
6    3
6    3
6    4
7    3
5    2
6    3
5    2
5    2
5    2
5    2
6    2
5    2
5    2
5    2
5    2
8    3
5    2
6    3
6    2
6    2
7    4
5    2
5    2
6    2
7    3
6    2
6    2
5    3
5    2
5    3
6    3
7    3
5    2
6    2
5    2
6    3
5    2
5    2
6    3
5    2
6    2
5    2
5    2
7    3
4    2
6    4
6    3
5    2
5    2
6    2
7    3
5    2
5    2
5    3
7    4
6    2
3    2
5    2
6    2
4    2
6    3
5    3
5    3
8    3
6    2
6    2
5    3
6    3
6    2
6    2
5    3
6    3
5    3
6    4
6    3
6    3
7    3
5    3
6    2
4    2
5    3
6    2
6    2
7    4
5    2
6    2
7    3
6    3
6    3
5    2
6    4
5    2
3    2
5    3
5    2
7    3
7    4
7    4
5    3
6    3
5    2
6    4
5    2
5    2
5    2
6    3
5    3
5    2
6    2
5    2
5    3
5    2
5    2
5    2
7    3
6    2
4    2
5    2
6    2
7    3
5    2
5    2
7    3
8    3
7    3
6    3
5    2
6    3
5    2
6    4
5    2
6    4
7    3
5    3
5    2
7    4
5    2
6    3
5    2
5    2
5    2
5    2
6    2
5    2
5    2
5    2
6    3
6    4
6    3
6    3
7    4
7    4
5    2
6    3
6    3
5    2
6    3
5    2
6    2
6    3
6    3
6    4
7    2
7    4
5    3
6    3
7    3
5    2
5    2
5    2
5    2
5    3
5    2
6    2
6    3
6    3
6    2
7    3
7    4
5    2
5    2
5    2
6    2
6    2
5    2
5    2
6    2
5    2
5    2
5    2
5    2
6    4
6    2
5    2
5    2
7    2
7    3
6    2
5    2
6    2

<h3>A bad fit for the data as the model has an accuracy of approximately 50%. <h5>This was just for an educational purpose